### ISSUE TITLE
Tessel disconnects if network is not discovered after length of time. 

### ISSUE THREAD

**Issue by facultymatt** [tessel/gprs-sim900#12]
I'm having a strange issue where code that worked fine earlier today is now faulting. I'm using the example script for the GPRS module. 

I've tried the following: 

1. Move closer to window for better reception
2. Up the delay between `gprs.on('ready')` and send sms.
3. Update Tessel firmware

Nothing seems to do the trick. I get the following log in console: 
```
{ message: 'Chain broke on AT+CMGS="<number redacted>"', type: 'Error', name: 'Error', stack: 'stack traceback:
	/app/node_modules/gprs-sim900/index.js:209: in function 'f'
	/app/node_modules/gprs-sim900/index.js:195: in function 'temp'
	/app/node_modules/gprs-sim900/postmaster.js:152: in function 'reply'
	/app/node_modules/gprs-sim900/postmaster.js:166: in function 'f'
	/app/node_modules/gprs-sim900/postmaster.js:86: in function '?'
	/app/node_modules/gprs-sim900/packetizer.js:152: in function '?'
	builtin/tessel.js:738: in function 'func'
	[T]: src/colony/lua/colony-node.lua:54: in function <[T]: src/colony/lua/colony-node.lua:53>' }
```

**Comment by davidhq** [comment]
I just got my tessel and I have the same problem:

```
david@eclipse:~/Projects/tessel$ tessel run gprs.js
TESSEL! Connected to TM-00-04-f0009a30-005e4357-109e25c2.
INFO Bundling directory /Users/david/Projects/tessel
INFO Deploying bundle (535.00 KB)...
INFO Running script...
GPRS module connected to Tessel. Searching for network...
Sending Text from a Tessel! to 38641555555 ...
Error: Chain broke on AT+CMGS="38641913862"
Error reading USB message endpoint: { [Error: LIBUSB_TRANSFER_ERROR] errno: 1 }
```
I went outside where the signal is ok for sure (inside it should be as well...)

Is there a fix for this?

**Comment by davidhq** [comment]
Now it worked once...

I waited a minute between connecting the tessel to computer and running the script... so that's good.. but what happened next is not so good:

```
TESSEL! Connected to TM-00-04-f0009a30-005e4357-109e25c2.
INFO Bundling directory /Users/david/Projects/tessel
INFO Deploying bundle (535.00 KB)...
INFO Running script...
GPRS module connected to Tessel. Searching for network...
Sending Text from a Tessel! to 38641913862 ...
Text sent: true
GPRS Module sent text # 79
Error reading USB message endpoint: { [Error: LIBUSB_TRANSFER_ERROR] errno: 1 }
Abort trap: 6
david@eclipse:~/Projects/tessel$ tessel run gprs.js
TESSEL? ERR! { [Error: LIBUSB_TRANSFER_STALL] errno: 4 }
```

Why are there USB issues when GPRS module is connected? This didn't happen with other modules so far...

**Comment by davidhq** [comment]
Actually it seems that USB cable (that came with tessel) is flaky... started having problems with other modules too... tried a different cable and for now no problems on any module...

**Comment by johnnyman727** [comment]
@davidhq thanks for reporting this - I'm glad you got it working. Do you mind if I close the issue since it's not related to the driver?

**Comment by davidhq** [comment]
Yes, close it :) -- I hope @facultymatt 's problems were also solved at the end....
