### ISSUE TITLE
Can we send a picture via GPRS or MMS?

### ISSUE THREAD

**Issue by fernandoybus** [tessel/gprs-sim900#29]
Can it?

**Comment by johnnyman727** [comment]
I haven't seen anyone use GPRS to send a picture yet but I have seen a [picture sent over MMS](https://projects.tessel.io/projects/mms-camera).

**Comment by fernandoybus** [comment]
This is great! Tks!
I can use that!

**Comment by fernandoybus** [comment]
Is this Tessel using wifi or GPRS?
I needed to use GPRS.

**Comment by johnnyman727** [comment]
That particular example is using Twilio over WiFi. You can check out [this GPRS project](https://projects.tessel.io/projects/tessel-tracker) which has an example of how to do a POST request using the GPRS module. You may be able to figure out how to send a photo using that procedure.

**Comment by fernandoybus** [comment]
I saw this project, but I dont know hoe to get the picture and send it over
GPRS.
Tks

**Comment by johnnyman727** [comment]
@fernandoybus, if you give me a better idea of what you're confused about, I may be able to point you in the right direction.

**Comment by fernandoybus** [comment]
To send a bit of info, i can add on the post request but for a picture, I
dont how to.

**Comment by johnnyman727** [comment]
Have you tried passing image data as the first argument to the [`sendPostRequest`](https://github.com/heikki/tessel-tracker-demo/blob/master/lib/commands.js#L36) function?

**Comment by fernandoybus** [comment]
That is my doubt exactly Jon.
Because if I am passing the string "tomato" or "potatoes", that seems easy.
But how would I pass a jpeg image?
Using this function sendPostRequest
<https://github.com/heikki/tessel-tracker-demo/blob/master/lib/commands.js#L36>,
can I just point to the jpeg file?

Best

On Mon, Jan 26, 2015 at 1:24 PM, Jon <notifications@github.com> wrote:

> Have you tried passing image data as the first argument to the
> sendPostRequest
> <https://github.com/heikki/tessel-tracker-demo/blob/master/lib/commands.js#L36>
> function?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tessel/gprs-sim900/issues/29#issuecomment-71541183>.
>



-- 
Best Regards,
Fernando Azevedo
"Winners never quit, quitters never win" - Vince Lombardi
Visit my previous works: y-bus.com

**Comment by johnnyman727** [comment]
@fernandoybus in this case, the program appears to be sending the data as a string. You'll want to base64 encode (`encodeURIComponent()`) the data so that the binary image can be transmitted as a string. You'll need to decode it on your server back into a Buffer. Does that help?

**Comment by fernandoybus** [comment]
Great! I think so! Let me try that!
Best
